import{createHash}from"node:crypto";import{NextResponse}from"next/server";import type Stripe from"stripe";import{createAdminClient}from"@/lib/supabase/admin";import{getStripe}from"@/lib/stripe";import{enforceRateLimit}from"@/lib/security/rate-limit";export const dynamic="force-dynamic";
export async function POST(request:Request){const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret)return NextResponse.json({error:"not_configured"},{status:503});const raw=await request.text(),hash=createHash("sha256").update(raw).digest("hex");let event:Stripe.Event;try{event=getStripe().webhooks.constructEvent(raw,request.headers.get("stripe-signature")??"",secret)}catch{const rate=await enforceRateLimit("webhook.stripe.invalid",20,300);return NextResponse.json({error:"invalid_signature"},{status:rate.allowed?400:429})}const db=createAdminClient()as any,object=event.data.object as any;
 if(event.type==="invoice.paid"){const subscriptionId=typeof object.parent?.subscription_details?.subscription==="string"?object.parent.subscription_details.subscription:typeof object.subscription==="string"?object.subscription:"";const intent=typeof object.payment_intent==="string"?object.payment_intent:"";const{error}=await db.rpc("process_subscription_invoice",{p_event_id:event.id,p_invoice_id:object.id,p_stripe_subscription:subscriptionId,p_payment_intent:intent,p_amount:object.amount_paid,p_currency:object.currency,p_payload_hash:hash});return error?NextResponse.json({error:"processing_failed"},{status:500}):NextResponse.json({received:true})}
 if(event.type.startsWith("customer.subscription.")){const localId=object.metadata?.obrador_subscription_id??object.metadata?.fuerza_subscription_id;const stripeStatus=event.type==="customer.subscription.deleted"?"cancelled":object.status==="active"?"active":object.status==="past_due"?"past_due":object.status==="unpaid"?"unpaid":"incomplete";if(localId){
  // paused/cancel_pending son estados que decide el propio sistema (pausa/
  // cancelación con 48h, no Stripe): un evento rutinario de Stripe que
  // reporte "active" no debe pisarlos, salvo que sea una cancelación real
  // (subscription.deleted) o un problema de cobro de verdad.
  const{data:existing}=await db.from("subscriptions").select("status").eq("id",localId).maybeSingle();
  const preserveLocal=stripeStatus==="active"&&(existing?.status==="paused"||existing?.status==="cancel_pending");
  const status=preserveLocal?existing.status:stripeStatus;
  await db.from("subscriptions").update({status,stripe_subscription_id:object.id,stripe_customer_id:typeof object.customer==="string"?object.customer:null,cancel_at_period_end:Boolean(object.cancel_at_period_end),current_period_start:object.items?.data?.[0]?.current_period_start?new Date(object.items.data[0].current_period_start*1000).toISOString():null,current_period_end:object.items?.data?.[0]?.current_period_end?new Date(object.items.data[0].current_period_end*1000).toISOString():null,...(status==="cancelled"?{cancelled_at:new Date().toISOString()}: {})}).eq("id",localId);await db.from("payment_events").upsert({stripe_event_id:event.id,event_type:event.type,processing_status:"processed",payload_hash:hash,processed_at:new Date().toISOString()},{onConflict:"stripe_event_id"})}return NextResponse.json({received:true})}
 if(event.type==="invoice.payment_failed"||event.type==="invoice.payment_action_required"){const sid=typeof object.subscription==="string"?object.subscription:"";await db.from("subscriptions").update({status:event.type.endsWith("action_required")?"requires_attention":"past_due",requires_attention_reason:event.type}).eq("stripe_subscription_id",sid);await db.from("payment_events").upsert({stripe_event_id:event.id,event_type:event.type,processing_status:"processed",payload_hash:hash,processed_at:new Date().toISOString()},{onConflict:"stripe_event_id"});return NextResponse.json({received:true})}
 const intent="payment_intent"in object&&typeof object.payment_intent==="string"?object.payment_intent:object.object==="payment_intent"?object.id:"",amount=object.amount??0,currency=object.currency??"eur";const{error}=await db.rpc("process_payment_event",{p_event_id:event.id,p_event_type:event.type,p_payment_intent:intent,p_amount:amount,p_currency:currency,p_payload_hash:hash});return error?NextResponse.json({error:"processing_failed"},{status:500}):NextResponse.json({received:true})}
